Zorgmode is an implementation of [[https://orgmode.org/][org mode]] for SublimeText 3.

[[https://travis-ci.org/dim-an/Zorgmode/][file:https://travis-ci.org/dim-an/Zorgmode.svg?branch=master]]

* Installation
: # Go to Packages directory (you can find it using menu Preferences → Browse Packages).
: cd /path/to/package/directory
: git clone git@github.com:dim-an/Zorgmode.git

* Short command overview
|            Command             |   Keys (Linux)  |       Context        |                    Comment                    |
|--------------------------------+-----------------+----------------------+-----------------------------------------------|
| zorg_cycle                     | tab             | - headline           | cycles through visibility of the current tree |
|--------------------------------+-----------------+----------------------+-----------------------------------------------|
| zorg_cycle_all                 | shift+tab       | - <any>              | cycles through visibility of all trees        |
|--------------------------------+-----------------+----------------------+-----------------------------------------------|
| zorg_move_node_up              | ctrl+shift+up   | - headline           | moves current section (or list item) up       |
|                                |                 | - list item          |                                               |
|--------------------------------+-----------------+----------------------+-----------------------------------------------|
| zorg_move_node_down            | ctrl+shift+down | - headline           | moves current section (or list item) down     |
|                                |                 | - list item          |                                               |
|--------------------------------+-----------------+----------------------+-----------------------------------------------|
| zorg_cycle_todo_state_forward  | alt+shift+right | - todo headline      | Cycles headline between todo item states      |
|                                |                 |                      | (=TODO= / =DONE= / =<empty state>= ) forward. |
|--------------------------------+-----------------+----------------------+-----------------------------------------------|
| zorg_cycle_todo_state_backward | alt+shift+left  | - todo headline      | Cycles headline between todo item states      |
|                                |                 |                      | (=TODO= / =DONE= / =<empty state>=) backward. |
|--------------------------------+-----------------+----------------------+-----------------------------------------------|
| zorg_toggle_checkbox           | alt+shift+left  | - checkbox list item | toggles checkbox between                      |
|                                | alt+shift+right |                      | unchecked ([ ]) and checked([X]) states       |
|--------------------------------+-----------------+----------------------+-----------------------------------------------|
| zorg_follow_link               | enter           | - link               | follow link                                   |
|--------------------------------+-----------------+----------------------+-----------------------------------------------|
| zorg_archive                   | ctrl+shift+A    | - headline           | move current section into archive             |
|--------------------------------+-----------------+----------------------+-----------------------------------------------|

* Org syntax crash course

#+BEGIN_SRC
org is a markup language similar to markdown or reStructuredText.

* Headlines (<- this is example of level 1 headline)
Line that starts with one or more stars is a headline.
** Example of level 2 headline
*** Example of level 3 headline
** Headline level 2 again

* Lists
org has various kinds of lists. You can use `-' `+' `*' to make an unordered list.
List items can span multiple lines.
 - item1
   continuation of item1 must be properly indented
 - item2
    and item2 has sublist:
    * child1
    * child2

Ordered lists can be created using numeral that is followed by either '.' or ')'.
 1. First item.
 2. Second item.

* Links
 - [[http://github.com/][GitHub]] <- this is a link
 - [[http://github.com/]] <- this is also a link
 - http://github.com/ <- this is yet another link

* Projects and checkbox item
Headline that starts with TODO / DONE is a project, like this
** TODO Explain projects and checkboxes
List item that starts with [ ] / [X] is a checkbox list item
 - [ ] unchecked list item
 - [X] checked list item
#+END_SRC

* Features
Currently Zorgmode doesn't provide all the features of [[https://orgmode.org/][emacs' org mode]] but it's quite usable.

** Cycle of visibility of sections
When cursor is over headline =zorg_cycle= (Linux: =Tab=) folds/unfolds corresponding section.

=zorg_cycle_all= (Linux: =Shift+Tab=) cycles among document visibility modes:
  - overview :: only top level headers are visible
  - contents :: all headers are visible but content is hidden
  - show all :: all the content is visible

** Hyperlinks
You can insert links in your document. Link can be in one of two forms:
  1. =https://github.com/dim-an/Zorgmode=
  2. =[[https://github.com/dim-an/Zorgmode]]=
  3. =[[https://github.com/dim-an/Zorgmode][Zorgmode homepage]]=

To follow a link you should place cursor over it use =zorg_follow_link= (Linux: =Enter=).
There are multiple types of links some of them will be opened using external application and others will be opened inside SublimeText.
For the latter ones you can use default SublimeText3 commands =Jump Back= / =Jump Forward= (from =Goto= menu) in order to get browser-like forward/backward navigation.

*** Link types
Zorgmode supports multiple types of links:
  1. Web links =[[http://github.com/]]=. Zorgmode will open them in your default web browser.
  2. File =[[file:/etc/passwd]]=. Zorgmode will open them using SublimeText.
  3. Files or directories =[[file+sys:/etc/]]=. Zorgmode will open them using your system default application (e.g. file manager for directories or media player for videos).
  4. Sections =[[Short command overview]]=. Zorgmode will set cursor to corresponding section.

*** Link abbreviations
You can create per document link abbreviations. To do this you should insert special line in any place of your document
: #+LINK: gh-user https://github.com/%s
Once line is inserted you can create links like this =[[gh-user:torvalds]]=. That link will be interpreted by Zorgmode as =[[https://github.com/torvalds]]=.

** Structural editing
=zorg_move_node_up= (Linux: =Ctrl+Shift+Up=) and =zorg_move_node_down= (Linux: =Ctrl+Shift+Down=) allows to swap current section or list item with its sibling.
Cursor must be positioned on the section headline or first line of list item.

** Todos and checkboxes
Headlines that start with =TODO= or =DONE= keyword are projects.
: * TODO Write documentation
: ** DONE Explain org syntax
: ** TODO Explain all the commands
Commands =zorg_cycle_todo_state_forward= (Linux: =Alt+Shift+Right=) and =zorg_cycle_todo_state_backward= (Linux: =Alt+Shift+Left=) cycle between project states (cursor must be over project headline):
  - =TODO=
  - =DONE=
  - empty state (not a project)

** Archive
Once you are done with your project you can move it to archive using =zorg_move_to_archive= (Linux: =Ctrl+Shift+A=). Archive filename is current filename with =_archive= suffix appended to it.

** Source code and example inclusion
There are multiple ways to include example or source code in your .org document:
  1. You can use ~#+BEGIN_EXAMPLE~ ~#+END_EXAMPLE~ markers:
    : this is example inside org text:
    : #+BEGIN_EXAMPLE
    : text of example
    : #+END_EXAMPLE
  2. If example is small you can start example line with colon:
    #+BEGIN_EXAMPLE
    This is example command:
    : git clone git@github.com/torvalds/linux
    #+END_EXAMPLE
  3.  Finaly you can use ~#+BEGIN_SRC~, ~#+END_SRC~ markers to include source code
      (and you can optionally specify what language is used):
      : This is code block:
      : #+BEGIN_SRC py
      : def func():
      :   print("Hello world!\n")
      : #+END_SRC
      List of supported languages includes: bash, c, c++/cpp/cxx, c#/cs, css,
      d, diff, erl, go, hs/haskell, java, js/JavaScript, lua, make, md/Markdown,
      ocaml, org, perl, php, py/python, r, rs, rst, rb, scala, sh, sql, tcl, xml, yml.

You can add spaces to indent your examples nicely:
#+BEGIN_SRC
  * Some list item with example command
    : git clone git@github.com/torvalds/linux
#+END_SRC

* Useful plugins
[[https://packagecontrol.io/packages/Table%20Editor][SublimeTableEditor]] plugin can help you edit tables in your org files.

* Other implementations
There is [[https://github.com/danielmagnussons/orgmode][another implementation]] of orgmode for SublimeText.
